print(stats.describe(notes1))
print("\n")
print(stats.describe(notes2))
print("\n")
print(stats.describe(notes3))
print("\n")
print("\n")
print(stats.describe(project1))
print("\n")
print(stats.describe(project2))
print("\n")
print(stats.describe(project3))


fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(X1[:, 0], X1[:, 1], c=labels)
ax.scatter(centroids[:, 0], centroids[:, 1], marker='*', c='#050505', s=1000)
plt.title('K Mean Classification')
plt.show()